version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ticket-management-system
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app:
    build: .
    container_name: nestjs_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://postgres:123456@postgres:5432/ticket-management-system?schema=public"
    command: npm run start:prod

volumes:
  postgres-data:
